"use client";
import { Fragment, useEffect, useMemo, useState } from "react";
import dynamic from "next/dynamic";
import { Download, Siren, MapPin, MessageCircle, Copy, Check, Printer, ChevronRight } from "lucide-react";
import { api, DOW, type Zone, type PatrolResp, type Deployment } from "@/lib/api";
import { cn } from "@/lib/utils";
import { Card, Kpi, Spinner } from "@/components/ui";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Slider } from "@/components/ui/slider";
import { Badge } from "@/components/ui/badge";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import {
  Table, TableBody, TableCell, TableHead, TableHeader, TableRow,
} from "@/components/ui/table";

const ZoneMap = dynamic(() => import("@/components/ZoneMap"), {
  ssr: false,
  loading: () => <div className="absolute inset-0 grid place-items-center text-muted-foreground">Loading map…</div>,
});

const clampHour = (n: number) => Math.max(0, Math.min(23, Math.round(n)));
const fmt = (n: number) => n.toLocaleString("en-IN");

export default function ForecastPage() {
  const [zones, setZones] = useState<Zone[] | null>(null);
  const [zonesErr, setZonesErr] = useState(false);

  const [dow, setDow] = useState(5); // Sat
  const [start, setStart] = useState(9);
  const [end, setEnd] = useState(13);
  const [teams, setTeams] = useState(8);
  const [area, setArea] = useState("");

  const [resp, setResp] = useState<PatrolResp | null>(null);
  const [planErr, setPlanErr] = useState(false);
  const [loading, setLoading] = useState(true);
  const [expanded, setExpanded] = useState<string | null>(null); // which team row is showing "Why here?"
  const [copied, setCopied] = useState(false);

  useEffect(() => {
    api.zones().then(setZones).catch(() => setZonesErr(true));
  }, []);

  const lo = Math.min(start, end);
  const hi = Math.max(start, end);
  const trimmedArea = area.trim();

  useEffect(() => {
    let alive = true;
    setLoading(true);
    setPlanErr(false);
    const t = setTimeout(() => {
      api
        .patrol({ weekday: DOW[dow], start_hour: lo, end_hour: hi, teams, area: trimmedArea || undefined })
        .then((r) => { if (alive) { setResp(r); setLoading(false); } })
        .catch(() => { if (alive) { setPlanErr(true); setLoading(false); } });
    }, 250);
    return () => { alive = false; clearTimeout(t); };
  }, [dow, lo, hi, teams, trimmedArea]);

  const plan = resp?.plan ?? [];
  const totalCatches = useMemo(() => plan.reduce((s, d) => s + d.pred_load, 0), [plan]);

  function downloadCsv() {
    if (!resp || plan.length === 0) return;
    const header = ["Team", "Deploy to", "Cell", "Lat", "Lon", "Exp catches", "Impact", "Avg severity", "Top violation"];
    const rows = plan.map((d) =>
      [d.team, d.label, d.gh6, d.lat, d.lon, d.pred_load, d.impact_score, d.avg_severity, d.top_violation]
        .map((v) => { const s = String(v); return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s; })
        .join(","));
    const csv = [header.join(","), ...rows].join("\n");
    const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `parkpulse-patrol-${DOW[dow]}-${lo}-${hi}.csv`;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  }

  // ---- shareable patrol briefing (free WhatsApp via wa.me deep link, no API needed) ----
  function buildBriefing(): string {
    if (!resp || plan.length === 0) return "";
    const head = `🚓 ParkPulse patrol plan — ${DOW[dow]}, ${resp.window}\n${plan.length} team${plan.length > 1 ? "s" : ""} · ${trimmedArea || "city-wide"}`;
    const lines = plan.map((d, i) =>
      `${i + 1}. ${d.team} → ${d.label}\n   ~${Math.round(d.pred_load)} expected · impact ${Math.round(d.impact_score)} · ${d.top_violation}`);
    return `${head}\n\n${lines.join("\n")}\n\nGenerated by ParkPulse`;
  }
  function teamBriefing(d: Deployment): string {
    return `🚓 ParkPulse — ${d.team}\nDeploy to: ${d.label}\n${DOW[dow]}, ${resp?.window ?? ""}\n~${Math.round(d.pred_load)} expected · impact ${Math.round(d.impact_score)}\nWatch for: ${d.top_violation}\n\nGenerated by ParkPulse`;
  }
  const waOpen = (text: string) => { if (text) window.open(`https://wa.me/?text=${encodeURIComponent(text)}`, "_blank"); };
  function shareWhatsApp() { waOpen(buildBriefing()); }
  function shareTeam(d: Deployment) { waOpen(teamBriefing(d)); }
  async function copyBriefing() {
    const text = buildBriefing();
    if (!text) return;
    try { await navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1500); } catch { /* ignore */ }
  }
  function printBriefing() {
    if (!resp || plan.length === 0) return;
    const rows = plan.map((d, i) =>
      `<tr><td>${i + 1}</td><td><b>${d.team}</b></td><td>${d.label}</td><td>${Math.round(d.pred_load)}</td><td>${Math.round(d.impact_score)}</td><td>${d.top_violation}</td></tr>`).join("");
    const html = `<!doctype html><html><head><meta charset="utf-8"><title>ParkPulse patrol plan</title><style>body{font-family:system-ui,Arial,sans-serif;padding:24px;color:#111}h1{font-size:18px;margin:0 0 2px}table{border-collapse:collapse;width:100%;font-size:13px;margin-top:10px}th,td{border:1px solid #ccc;padding:6px 8px;text-align:left}th{background:#f3f4f6}</style></head><body><h1>🚓 ParkPulse patrol plan — ${DOW[dow]}, ${resp.window}</h1><p>${plan.length} teams · ${trimmedArea || "city-wide"}</p><table><thead><tr><th>#</th><th>Team</th><th>Deploy to</th><th>Exp. catches</th><th>Impact</th><th>Top violation</th></tr></thead><tbody>${rows}</tbody></table><p style="margin-top:16px;color:#666;font-size:11px">Generated by ParkPulse</p></body></html>`;
    const w = window.open("", "_blank");
    if (w) { w.document.write(html); w.document.close(); w.focus(); w.print(); }
  }

  if (zonesErr)
    return (
      <div className="p-8 text-destructive">
        Can&apos;t reach the API. Start the backend: <code>python fullstack/backend/main.py</code> (:8000).
      </div>
    );

  return (
    <div className="mx-auto max-w-6xl px-6 py-10">
      <header className="mb-6 flex items-start gap-3">
        <div className="mt-1 grid h-9 w-9 shrink-0 place-items-center rounded-lg bg-primary/15 text-primary">
          <Siren className="h-5 w-5" />
        </div>
        <div>
          <h1 className="text-3xl font-bold leading-tight">Forecast &amp; Patrol Planner</h1>
          <p className="mt-1.5 max-w-2xl text-muted-foreground">
            Pick a day and a shift window — we forecast where violations will cluster and place every team
            where congestion will build, before it does.
          </p>
        </div>
      </header>

      {/* controls */}
      <Card className="mb-6">
        <div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-5">
          <div className="space-y-1.5">
            <Label>Weekday</Label>
            <Select value={String(dow)} onValueChange={(v) => setDow(Number(v))}>
              <SelectTrigger className="w-full"><SelectValue /></SelectTrigger>
              <SelectContent>
                {DOW.map((d, i) => <SelectItem key={d} value={String(i)}>{d}</SelectItem>)}
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-1.5">
            <Label>Shift start (hour)</Label>
            <Input type="number" min={0} max={23} value={start}
              onChange={(e) => setStart(clampHour(Number(e.target.value)))} />
          </div>
          <div className="space-y-1.5">
            <Label>Shift end (hour)</Label>
            <Input type="number" min={0} max={23} value={end}
              onChange={(e) => setEnd(clampHour(Number(e.target.value)))} />
          </div>
          <div className="space-y-1.5">
            <div className="flex items-center justify-between">
              <Label>Teams</Label>
              <span className="text-sm font-semibold tabular-nums text-primary">{teams}</span>
            </div>
            <Slider min={1} max={20} step={1} value={[teams]}
              onValueChange={(v) => setTeams(Array.isArray(v) ? v[0] : v)} className="py-2.5" />
          </div>
          <div className="space-y-1.5">
            <Label>Area (optional)</Label>
            <Input type="text" value={area} placeholder="e.g. Koramangala"
              onChange={(e) => setArea(e.target.value)} />
          </div>
        </div>
      </Card>

      {/* KPIs */}
      <div className="mb-6 grid grid-cols-2 gap-3 md:grid-cols-4">
        <Kpi label="Teams placed" value={resp ? fmt(resp.teams) : "—"} />
        <Kpi label="Shift window" value={resp ? resp.window : "—"} hint={DOW[dow]} />
        <Kpi label="Forecast catches" value={resp ? fmt(Math.round(totalCatches)) : "—"} hint="summed predicted load" />
        <Kpi label="Focus area" value={trimmedArea || "All Bengaluru"} hint={trimmedArea ? "filtered" : "city-wide"} />
      </div>

      {/* map */}
      <Card className="mb-6 overflow-hidden p-0">
        <div className="relative h-[480px] w-full">
          {zones ? <ZoneMap zones={zones} plan={plan} />
                 : <div className="absolute inset-0 grid place-items-center text-muted-foreground">Loading map…</div>}
          <div className="pointer-events-none absolute left-4 top-4 flex flex-wrap gap-2">
            <Badge variant="secondary" className="gap-1"><MapPin className="h-3 w-3" /> forecast hotspots</Badge>
            <Badge className="gap-1"><Siren className="h-3 w-3" /> {plan.length || teams} teams</Badge>
          </div>
        </div>
      </Card>

      {/* deployment table */}
      <Card>
        <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
          <div>
            <h3 className="text-lg font-bold">Deployment plan</h3>
            <p className="mt-1 text-sm text-muted-foreground">
              {resp ? `${DOW[dow]}, ${resp.window} — ${plan.length} ${plan.length === 1 ? "team" : "teams"}` : "Building plan…"}
            </p>
          </div>
          <div className="flex flex-wrap items-center gap-2">
            <Button variant="outline" size="sm" onClick={downloadCsv} disabled={!resp || plan.length === 0}>
              <Download /> CSV
            </Button>
            <Button variant="outline" size="sm" onClick={shareWhatsApp} disabled={!resp || plan.length === 0}>
              <MessageCircle /> WhatsApp
            </Button>
            <Button variant="outline" size="sm" onClick={copyBriefing} disabled={!resp || plan.length === 0}>
              {copied ? <Check /> : <Copy />} {copied ? "Copied" : "Copy"}
            </Button>
            <Button variant="outline" size="sm" onClick={printBriefing} disabled={!resp || plan.length === 0}>
              <Printer /> Print
            </Button>
          </div>
        </div>

        {loading ? (
          <Spinner label="Forecasting hotspots…" />
        ) : planErr ? (
          <div className="py-10 text-center text-sm text-destructive">
            Couldn&apos;t build a plan for that window. Try a different day, window, or area.
          </div>
        ) : plan.length === 0 ? (
          <div className="py-10 text-center text-sm text-muted-foreground">
            No forecast hotspots matched these filters. Widen the window or clear the area.
          </div>
        ) : (
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Team</TableHead>
                <TableHead>Deploy to</TableHead>
                <TableHead>Top violation</TableHead>
                <TableHead className="text-right">Exp. catches</TableHead>
                <TableHead className="w-[160px]">Impact</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {plan.map((d) => {
                const open = expanded === d.team;
                const jf = Math.round((d.junction_frac ?? 0) * 100);
                const mf = Math.round((d.main_road_frac ?? 0) * 100);
                return (
                  <Fragment key={d.team}>
                    <TableRow className="cursor-pointer" onClick={() => setExpanded(open ? null : d.team)}>
                      <TableCell className="font-semibold text-primary">
                        <span className="inline-flex items-center gap-1.5">
                          <ChevronRight className={cn("h-3.5 w-3.5 text-muted-foreground transition-transform", open && "rotate-90")} />
                          {d.team}
                        </span>
                      </TableCell>
                      <TableCell>
                        <div className="truncate font-medium">{d.label}</div>
                        <div className="text-[11px] text-muted-foreground">{d.gh6}</div>
                      </TableCell>
                      <TableCell className="text-muted-foreground">{d.top_violation}</TableCell>
                      <TableCell className="text-right font-semibold tabular-nums">{fmt(d.pred_load)}</TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <div className="h-1.5 w-20 overflow-hidden rounded-full bg-secondary">
                            <div className="h-full bg-primary"
                              style={{ width: `${Math.max(0, Math.min(100, d.impact_score))}%` }} />
                          </div>
                          <span className="w-7 text-right text-xs tabular-nums text-muted-foreground">
                            {Math.round(d.impact_score)}
                          </span>
                        </div>
                      </TableCell>
                    </TableRow>
                    {open && (
                      <TableRow className="bg-muted/20 hover:bg-muted/20">
                        <TableCell colSpan={5} className="py-3">
                          <div className="space-y-1.5 text-xs">
                            <div className="font-medium text-foreground">Why {d.team} is deployed here</div>
                            <ul className="space-y-1 text-muted-foreground">
                              <li>
                                <span className="font-medium text-foreground">~{Math.round(d.pred_load)} expected catches</span>{" "}
                                for {DOW[dow]}, {resp?.window} — the highest-forecast zone left after spacing teams apart.
                              </li>
                              <li>
                                Congestion Impact <span className="font-medium text-foreground">{Math.round(d.impact_score)}/100</span> —{" "}
                                {jf}% of violations here sit at junctions, {mf}% on main roads (high flow-impact).
                              </li>
                              <li>
                                Most common: <span className="font-medium text-foreground">{d.top_violation}</span>
                                {d.avg_severity != null && <> · avg severity {Number(d.avg_severity).toFixed(2)}</>}.
                              </li>
                            </ul>
                            <Button variant="ghost" size="sm" className="h-7 gap-1 px-2 text-[11px]"
                              onClick={(e) => { e.stopPropagation(); shareTeam(d); }}>
                              <MessageCircle className="h-3 w-3" /> Share this team to WhatsApp
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    )}
                  </Fragment>
                );
              })}
            </TableBody>
          </Table>
        )}
        <p className="mt-4 text-xs text-muted-foreground">
          Tap any team for <span className="text-foreground">why it&apos;s placed there</span> · share the plan to WhatsApp,
          copy, or print it for roll-call. Every team starts where congestion will build, before it does.
        </p>
      </Card>
    </div>
  );
}
